:servers:
- :host: irc.freenode.net
  :nick: MyBelugaBot
  :channels:
    - "#magmawiki"
  :plugins: 
    - pingback
- :host: irc.newnet.net
  :nick: MyBelugaBot2
  :channels:
    - "##emilysroom"
  :plugins:
